#!/bin/bash

while read -r line; do
    number=$(echo "$line" | cut -d':' -f1)
    factors=$(factor "$number" | awk -F ': ' '{ print $2 }')

    # Split factors into two numbers
    factor1=$(echo "$factors" | awk '{print $1}')
    factor2=$(echo "$factors" | awk '{print $2}')

    echo "$number=$(($number / $factor1))*$factor1"
done < "$1"
