#!/usr/bin/python3
import sys


def main():
    if len(sys.argv) != 2:
        print("Usage: rsa <file>")
        sys.exit(1)
    input_file = sys.argv[1]
    try:
        with open(input_file, 'r') as file:
            for line in file:
                num = int(line.strip())
                print("{:d}=".format(num), end="")
                if num % 2 == 0:
                    print("{}*2".format(num//2))
                    continue
                for i in range(3, num, 2):
                    if num % i == 0:
                        factor = num//i
                        for j in range(3, factor, 2):
                            if factor % j == 0 or i % j == 0:
                                break
                        print("{}*{}".format(factor, i))
                        break

    except (FileNotFoundError, ValueError):
        print(f"Error: File '{input_file}' not found.")
        print("OR use natural numbers")
        sys.exit(1)


if __name__ == "__main__":
    main()
